name: Docker Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-backend:
    name: Build Backend Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build backend Docker image
        uses: docker/build-push-action@v7
        with:
          context: ./backend
          push: false
          tags: thinkora-backend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-frontend:
    name: Build Frontend Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build frontend Docker image
        uses: docker/build-push-action@v7
        with:
          context: ./frontend
          push: false
          tags: thinkora-frontend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
